CREATE TABLE IF NOT EXISTS addresses (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    apelativ VARCHAR(10) NOT NULL DEFAULT 'Dl.',
    prenume VARCHAR(100) NOT NULL,
    nume VARCHAR(100) NOT NULL,
    tara VARCHAR(100) NOT NULL DEFAULT 'Romania',
    adresa1 TEXT NOT NULL,
    adresa2 TEXT,
    cod_postal VARCHAR(20) NOT NULL,
    oras VARCHAR(100) NOT NULL,
    implicit_facturare BOOLEAN NOT NULL DEFAULT false,
    implicit_livrare BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS addresses_user_id_idx ON addresses(user_id);

ALTER TABLE addresses ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS apelativ VARCHAR(10) NOT NULL DEFAULT 'Dl.';
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS prenume VARCHAR(100);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS nume VARCHAR(100);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS tara VARCHAR(100) NOT NULL DEFAULT 'Romania';
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS adresa1 TEXT;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS adresa2 TEXT;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS cod_postal VARCHAR(20);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS oras VARCHAR(100);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS implicit_facturare BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS implicit_livrare BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
