ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS awb_number VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS awb_status VARCHAR(100) DEFAULT 'Not Generated',
ADD COLUMN IF NOT EXISTS awb_carrier VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS awb_pdf_url TEXT DEFAULT NULL;
